In [22]:
import pandas as pd
import numpy as np
import datetime as dt
import sklearn as sk
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [6]:
readmit_model1 = pd.read_csv(r'C:\Users\brthompson\bt_school\data\interim\readmit_model1.csv')
mort_model1 = pd.read_csv(r'C:\Users\brthompson\bt_school\data\interim\mort_model1.csv')

In [7]:
readmit_model1.head()

,age,los,GENDER_F,GENDER_M,ADMISSION_TYPE_ELECTIVE,ADMISSION_TYPE_EMERGENCY,ADMISSION_TYPE_NEWBORN,ADMISSION_LOCATION_** INFO NOT AVAILABLE **,ADMISSION_LOCATION_CLINIC REFERRAL/PREMATURE,ADMISSION_LOCATION_EMERGENCY ROOM ADMIT,...,DIAGNOSIS_STERNAL WOUND INFECTION.1,DIAGNOSIS_STROKE-TRANSIENT ISCHEMIC ATTACK.1,DIAGNOSIS_STROKE/TIA.1,DIAGNOSIS_STROKE;TELEMETRY;TRANSIENT ISCHEMIC ATTACK.1,DIAGNOSIS_SUBARACHNOID HEMATOMA.1,DIAGNOSIS_SUBARACHNOID HEMORRHAGE.1,DIAGNOSIS_TRAUMA.1,DIAGNOSIS_TYLENOL OVERDOSE.1,"DIAGNOSIS_URINARY TRACT INFECTION,PYELONEPHRITIS.1",readmit
0,0.000000,4,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,76.575342,11,0,1,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,47.876712,7,1,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0.000000,2,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,65.983562,16,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
#Check balance - do not need to balance this dataset
readmit_model1['readmit'].value_counts()

0    43262
1    30244
Name: readmit, dtype: int64

In [9]:
mort_model1.head()

,age,los,ADMISSION_TYPE_ELECTIVE,ADMISSION_TYPE_EMERGENCY,ADMISSION_TYPE_NEWBORN,ADMISSION_TYPE_URGENT,ADMISSION_LOCATION_** INFO NOT AVAILABLE **,ADMISSION_LOCATION_EMERGENCY ROOM ADMIT,ADMISSION_LOCATION_HMO REFERRAL/SICK,ADMISSION_LOCATION_PHYS REFERRAL/NORMAL DELI,...,DIAGNOSIS_SUBDURAL HEMATOMA.1,DIAGNOSIS_SYNCOPE;TELEMETRY.1,DIAGNOSIS_UNSTABLE ANGINA.1,DIAGNOSIS_UNSTABLE ANGINA\CATH.1,DIAGNOSIS_UPPER GI BLEED.1,DIAGNOSIS_UPPER GI BLEED;TELEMETRY.1,DIAGNOSIS_URINARY TRACT INFECTION.1,DIAGNOSIS_VOMITING.1,DIAGNOSIS_WEAKNESS.1,HOSPITAL_EXPIRE_FLAG
0,0.000000,4,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,76.575342,11,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,47.876712,7,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.000000,2,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,65.983562,16,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [10]:
#Check balance - will need to balance this dataset
mort_model1['HOSPITAL_EXPIRE_FLAG'].value_counts()

0    67186
1     6320
Name: HOSPITAL_EXPIRE_FLAG, dtype: int64

In [15]:
#Start with readmit model since the data is already balanced
#Split dependent and independent variables
Xad = readmit_model1.drop(['readmit'], 1) #Features
Yad = readmit_model1['readmit'] #Target variable

In [16]:
#Split the data into training and test
X_train,X_test,y_train,y_test=train_test_split(Xad,Yad,test_size=0.25,random_state=0)

In [19]:
logreg = LogisticRegression()

In [20]:
logreg.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
y_pred=logreg.predict(X_test)

In [23]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[8748, 2155],
       [2640, 4834]], dtype=int64)